[package]
name = "rs-img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
image_compressor = "1.3.0"
num_cpus = "1.16.0"
webp = "0.2.3"
image = "0.24.6"
rayon = "1.7.0"
camino = "1.1.4"
dirs = "5.0.1"
fltk = "1.4.7"
flemish = "0.4.1"

# optimize for size
[profile.release]
strip = true
lto = true
opt-level = "z"
debug = 0
overflow-checks = false
panic = "abort"
codegen-units = 1
