[package]
name = "rs-img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
inquire = "0.6.0"
image_compressor = "1.3.0"
num_cpus = "1.15.0"
ansi_term = "0.12.1"
webp = "0.2.2"
image = "0.24.6"
spinoff = "0.7.0"
rayon = "1.7.0"

# optimize for size
[profile.release]
strip = true
lto = true
opt-level = "z"
debug = 0
overflow-checks = false
panic = "abort"
codegen-units = 1
